source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'Lottery_iOS' do
pod 'AFNetworking', '~> 3.0'
end

pod 'SVProgressHUD'

pod 'LBXScan',git:'https://github.com/MxABC/LBXScan.git'

pod 'LBXAlertAction'

pod 'MJExtension'

pod 'MJRefresh'

pod 'IQKeyboardManager'

